name: Build Launcher

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Check out files
        uses: actions/checkout@v5

      - name: Build launcher
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" -arch=x64 -host_arch=x64
          cl /nologo /O2 /MT /DUNICODE /D_UNICODE /EHsc Launcher.cpp /link /SUBSYSTEM:WINDOWS /OUT:"Your Game.exe"
          if not exist "Your Game.exe" exit /b 1

      - name: Upload launcher
        uses: actions/upload-artifact@v6
        with:
          name: launcher-exe
          path: Your Game.exe
